### ISSUE TITLE
crash when loading world (Quality's Delight)

### ISSUE THREAD

**Issue by kaairu** [MtcLeo05/QualityCrops#3]
couldnt find the source for quality delight so I'm reporting this here 
[latest.log](https://github.com/MtcLeo05/QualityCrops/files/12980681/latest.log)
[crash-2023-10-17_20.36.11-client.txt](https://github.com/MtcLeo05/QualityCrops/files/12980696/crash-2023-10-17_20.36.11-client.txt)

**Comment by MtcLuna05** [comment]
thanks for the report!
once i have some free time I'll get on it

**Comment by MtcLuna05** [comment]
Fixed in version 1.5.1 for both 1.19.2 and 1.20.1 (File will become available in a bit)
