### ISSUE TITLE
[Forge - 1.19.2]: Allow downgrading from all qualities

### ISSUE THREAD

**Issue by SiverDX** [MtcLeo05/QualityCrops#9]
Currently only Iron -> None is supported

Recommend adding:
- Gold -> Iron
- Diamond -> Gold

**Comment by MtcLuna05** [comment]
My intention was making all of them downgradable to none so you can use them in normal recipes, not being able to convert an higher quality to lower. 
This was mainly to not having to add the normal variant tag to all items (like forge:carrots to quality carrots) as there are some items which don't have a tag which would allow them to be used in normal crafting, and I decided to just add the recipe to convert them to everyt item.

**Comment by SiverDX** [comment]
Currently gold and diamond are non-convertible
